### ISSUE TITLE
Undefined method BladeCompiler::getRawTags(). Cannot compile views on Laravel 5

### ISSUE THREAD

**Issue by vaaguirre** [Flynsarmy/laravel-db-blade-compiler#14]
I've installed the package (versión 2 for laravel 5) but I'm getting this:

    FatalErrorException in DbBladeCompiler.php line 18:
    Call to undefined method Illuminate\View\Compilers\BladeCompiler::getRawTags()

If I comment out that line I then get this:

    FatalErrorException in DbBladeCompiler.php line 21:
    Call to undefined method Illuminate\View\Compilers\BladeCompiler::getExtensions()

If I comment out both lines then it works perfectly, but obviously this will be overwritten. Why is this happening?

**Comment by manooweb** [comment]
Hi !
getRawTags() and getExtensions accessor exist only since laravel 5.1 
https://laravel.com/api/5.1/Illuminate/View/Compilers/BladeCompiler.html

I prefer to access directly to extensions and rawTags members of BladeCompiler class than comment these lines.

```
       $this->rawTags     = $blade->rawTags;
       $this->extensions  = $blade->extensions;

```
