### ISSUE TITLE
Use StyleCI

### ISSUE THREAD

**Issue by danieliancu** [Flynsarmy/laravel-db-blade-compiler#16]
Hello!

Just a friendly invitation to activate https://styleci.io for your project.

**Comment by Flynsarmy** [comment]
Spam

**Comment by danieliancu** [comment]
You must be kidding. I don't event work for them. I looked through the source code of the package and I saw code formatted in all directions...

**Comment by danieliancu** [comment]
Sorry if you consider it spam...

**Comment by danieliancu** [comment]
Anyway, thank you very much for this awesome package.
Great work!
