### ISSUE TITLE
htmlentities() expects parameter 1 to be string, object given (View: )

### ISSUE THREAD

**Issue by altafhussain10** [Flynsarmy/laravel-db-blade-compiler#20]
Hi, 
First of all thanks for a great package. 
I am using it with laravel 5.2.30, and it always gives me error htmlentities() expects parameter 1 to be string, object given (View: ). I am not sure why it gives me this error. I am using the below code in my controller action. 

`$block = \App\Models\CmsBlock::where('slug', 'main-menu')->where('active', 1)->first();

 return \Flynsarmy\DbBladeCompiler\Facades\DbView::make($block, [], [], 'content')->render();`

A screenshot with the complete exception is also attached. It will be very helpful and kind of you to advice about this issue. 

Thank you
<img width="970" alt="screen shot 2016-04-22 at 1 22 16 pm" src="https://cloud.githubusercontent.com/assets/4163772/14738956/646dd436-088d-11e6-87ab-6cfebf68330c.png">

**Comment by me2bits** [comment]
What's in DB field?

**Comment by altafhussain10** [comment]
Thanks for your response. The field in DB is "content". If i dont pass the field, i still get the same error as above.

**Comment by lbeauvisage** [comment]
@altafhussain10 Look's like a Blade Error when using {{$var}} instead of {!! $var !!}
