### ISSUE TITLE
Update to support compatibility with laravel 5.4

### ISSUE THREAD

**Issue by smartevil** [Flynsarmy/laravel-db-blade-compiler#25]
There is compatibility issue with laravel 5.4, after running php artisan vendor:publish
I got the following error:
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Application::share()

**Solution:**
On DbBladeCompilerServiceProvider.php, line 39
$this->app['dbview'] = $this->app->share(function($app)
change to:
$this->app->singleton('dbview', function ($app)

**Comment by Flynsarmy** [comment]
Thanks. Fixed in https://github.com/Flynsarmy/laravel-db-blade-compiler/releases/tag/5.4.0
