### ISSUE TITLE
Laravel 5.5: Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by KoenLav** [Flynsarmy/laravel-db-blade-compiler#35]
Using a singleton is recommended.

**Comment by lminor** [comment]
This was resolved a while back. If you check this closed issue https://github.com/Flynsarmy/laravel-db-blade-compiler/issues/25 it is in the latest releases. Check your composer release as I had the same issue when following the README.md you pull release 2.0.2 but the latest is actually 5.4.2.

**Comment by KoenLav** [comment]
Thanks!
