### ISSUE TITLE
Class 'App\Http\Controllers\DbView' not found

### ISSUE THREAD

**Issue by xtremewe** [Flynsarmy/laravel-db-blade-compiler#38]
I have successfully installed the package via composer. In config/app.php i have also added the aliases and provider.

Under Providers array
Flynsarmy\DbBladeCompiler\DbBladeCompilerServiceProvider::class,

Under aliases
'DbView' => Flynsarmy\DbBladeCompiler\Facades\DbView::class

I am using following code in my controller

$template = Template::findOrFail($id);
return DbView::make($template)->field('template')->with(['client_name' => 'Bar'])->render();

What could be wrong?

**Comment by xtremewe** [comment]
Template Model do exist and I have a CRUD successfully working.

**Comment by glennjacobs** [comment]
`use DbView;`?

**Comment by xtremewe** [comment]
Can you please explain, what do I have to changes? Do you mean use DbView; at the end aliases line instead of DbView::class

**Comment by extsalt** [comment]
php artisan config:cache
then
composer du

**Comment by nickfls** [comment]
@xtremewe 
The issue is likely resolved for you, however, just in case, it looks like DbView was not properly imported:

```php
<?php

namespace App\Http\Controllers;

use DbView;

class SomeController extends Controller 
{
...
}
```
