### ISSUE TITLE
Declaration of DbView::render must be compatible with View::render

### ISSUE THREAD

**Issue by junaidnasir** [Flynsarmy/laravel-db-blade-compiler#39]
Kindly make a new release. don't want to set to master@dev
`PHP Fatal error:  Declaration of Flynsarmy\DbBladeCompiler\DbView::render(?Closure $callback = NULL) must be compatible with Illuminate\View\View::render(?callable $callback = NULL) in /home/vagrant/code/igniter/vendor/flynsarmy/db-blade-compiler/src/Flynsarmy/DbBladeCompiler/DbView.php on line 9
`

**Comment by zarianec** [comment]
Totally agree. It's only package that prevents me from upgrading to 7.2.

**Comment by Flynsarmy** [comment]
Done https://github.com/Flynsarmy/laravel-db-blade-compiler/releases/tag/5.4.3
