### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Besmer** [Flynsarmy/laravel-db-blade-compiler#43]
file_put_contents(%dir to project%/storage/app/db-blade-compiler/views/17abf6bcdeeb5ac643c79833c995cb95): failed to open stream: No such file or directory

**Comment by dakisan** [comment]
I also have this issue

**Comment by Besmer** [comment]
I fixed it in fork:
https://github.com/Besmer/laravel-db-blade-compiler

**Comment by marcmascarell** [comment]
@Besmer Why don't you open a merge request so @Flynsarmy can you apply your changes? I need them :/

**Comment by marcmascarell** [comment]
@Flynsarmy Can you point out which is the probable cause of this and how to fix it?

**Comment by marcmascarell** [comment]
I ended up creating the folder myself: `mkdir -p storage/app/db-blade-compiler/view`

**Comment by Flynsarmy** [comment]
I don't use this package anymore and haven't tested in a long time. If you come up with a fix (such as the one @Besmer made, submit it in a PR and I'll merge.
