### ISSUE TITLE
New tag needed, update docs

### ISSUE THREAD

**Issue by pvankouteren** [Flynsarmy/laravel-db-blade-compiler#49]
dev-master fixes some of the open issues that are raised. Perhaps it's a good idea to create a new tag and refer to this in the docs.

Also for publishing you might want to update the command to

`
php artisan vendor:publish --provider="Flynsarmy\DbBladeCompiler\DbBladeCompilerServiceProvider"
`

Instead of a vendor publish for all

**Comment by Flynsarmy** [comment]
The 5.4.4 release includes all the latest commits except my readme one just now doesn't it? (thank you for that btw)
