### ISSUE TITLE
Is it compatible with Laravel 8 ?

### ISSUE THREAD

**Issue by foxmedo** [Flynsarmy/laravel-db-blade-compiler#54]
Dears , 

is this package is compatible with Laravel 8 

Best regards

**Comment by edwinricaurte** [comment]
I having issues with Laravel 9, for some reason is just showing HTTP ERROR 500 and when I reload the php8.1-fpm shows the following error message:

Symfony\Component\ErrorHandler\Error\FatalError: Declaration of Flynsarmy\DbBladeCompiler\DbView::offsetExists($key) must be compatible with Illuminate\View\View::offsetExists($key): bool in file /home/orangeugoing/site/vendor/flynsarmy/db-blade-compiler/src/Flynsarmy/DbBladeCompiler/DbView.php on line 164

**Comment by brandonjbegle** [comment]
I'm having the same issue with Laravel 9. The reason is because the offsetExists function that overrides the default does not have the return type (bool) in this package. It needs to be updated.

**Comment by brandonjbegle** [comment]
> I'm having the same issue with Laravel 9. The reason is because the offsetExists function that overrides the default does not have the return type (bool) in this package. It needs to be updated.

I submitted a pull requests to update. In the mean time, I forked the repo and updated compatibility to Laravel 9. So you can use my fork temporarily until this repo is updated.

In composer.json

`"repositories": [
   ...
    {
      "type": "vcs",
      "url": "https://github.com/begleweyer/laravel-db-blade-compiler.git"
    }
  ],`
  
  
  and 
  
  `"flynsarmy/db-blade-compiler": "dev-laravel-9",`

**Comment by Flynsarmy** [comment]
Merged. Thanks for the PR!
