### ISSUE TITLE
When we have 2 rendering views

### ISSUE THREAD

**Issue by llechevbulpont** [Flynsarmy/laravel-db-blade-compiler#6]
> $compiledViewHtml = DbView::make($newsletter, $contact->toArray(), array(), 'html');
> $compiledViewPlain = DbView::make($newsletter, $contact->toArray(), array(), 'plain');
> $data['html'] = $compiledViewHtml->render();
> $data['plain'] = $compiledViewPlain->render();

This code returns only the Plain view! The $compiledViewPlain overrides the existing         $compiledViewHtml attributes maybe?

**Comment by me2bits** [comment]
@llechevbulpont 
Can I see your view code?

**Comment by jausions** [comment]
The problem as I currently see it is that DbView::make() doesn't return a new instance of the view. So if you call DbView::make() several times, the last Model passed wins. This is seriously limiting for me. What is actually needed is a Factory. I will see if I can submit a PR once I get something worked out.
