### ISSUE TITLE
Laravel v5 Support

### ISSUE THREAD

**Issue by me2bits** [Flynsarmy/laravel-db-blade-compiler#9]
Hi
It seems the package is not compatible with Laravel v5. 
Do you have a plan for Laravel v5?

**Comment by Flynsarmy** [comment]
I don't have any plans to upgrade but it shouldn't be difficult. PRs are welcome.

**Comment by me2bits** [comment]
Maybe!
I want to improve it and make it compatible with Laravel 5. How can I do that? May you help me to start from where? Can you help me to know references?

**Comment by Flynsarmy** [comment]
You need to fork this repo, make your adjustments into a new branch, then send a pull request. Googling git tutorials will teach you how to do all that.

**Comment by me2bits** [comment]
I know about git and process of PR. I do not know how make a package for Laravel 5. This is my first time. I think I should go to Laravel site and find the document. Is it true?

**Comment by Flynsarmy** [comment]
You shouldn't need to change anything about the package. just fix whatever error it is you're getting (you didn't specify).

**Comment by me2bits** [comment]
OK, Thanks. I'm going to do that.

**Comment by me2bits** [comment]
It's ready.
I made a push request.

**Comment by Flynsarmy** [comment]
Update released. Just waiting on packagist to update now. Thanks for the fix!

**Comment by me2bits** [comment]
Thanks :-)
